version: '1.0'
services:
  wecombot:
    image: crpi-40d64hpk9w60wnns.cn-shanghai.personal.cr.aliyuncs.com/bedlims/wecombot:0.1
    container_name: wecombot
    env_file:
      - wecombot.env
    restart: unless-stopped